version: '2'

services:
  gnosis_management:
    build:
      context: .
      dockerfile: ManagementDockerfile
    image: gnosispm/gnosis-management
    working_dir: /gnosis-management
    command: sh gnosis_management_setup.sh
    ports:
      - "5000:5000"
      - "8545"
      - "8000"
